In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('F:\YBI Foundation\Dataset-main/Womens Clothing E-Commerce Reviews.csv')

In [3]:
df.shape

(23486, 11)

In [4]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [5]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [6]:
df[df['Review Text']==""]= np.NaN

In [7]:
df['Review Text'].fillna('No Review',inplace = True)

In [8]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Unnamed: 0               23486 non-null  float64
 1   Clothing ID              23486 non-null  float64
 2   Age                      23486 non-null  float64
 3   Title                    19676 non-null  object 
 4   Review Text              23486 non-null  object 
 5   Rating                   23486 non-null  float64
 6   Recommended IND          23486 non-null  float64
 7   Positive Feedback Count  23486 non-null  float64
 8   Division Name            23472 non-null  object 
 9   Department Name          23472 non-null  object 
 10  Class Name               23472 non-null  object 
dtypes: float64(6), object(5)
memory usage: 2.0+ MB


In [11]:
x = df['Review Text']
y = df['Rating']

In [12]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,stratify = y,random_state = 192529)

In [14]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer(lowercase = True,analyzer = 'word',ngram_range = (2,3),stop_words = 'english',max_features = 5000)

In [17]:
x_train = cv.fit_transform(x_train)

In [18]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 fit', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [19]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
x_test = cv.fit_transform(x_test)

In [21]:
cv.get_feature_names_out(x_test)

array(['00p 0p', '10 12', '10 bought', ..., 'yellow color',
       'yesterday store', 'yoga pants'], dtype=object)

In [22]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
from sklearn.naive_bayes import MultinomialNB

In [24]:
model = MultinomialNB()

In [25]:
model.fit(x_train,y_train)

MultinomialNB()

In [26]:
predictions = model.predict(x_test)

In [27]:
predictions.shape

(7046,)

In [28]:
predictions

array([5., 5., 5., ..., 5., 1., 1.])

In [29]:
model.predict_proba(x_test)

array([[0.03968516, 0.04816235, 0.05614999, 0.05949307, 0.79650943],
       [0.23564958, 0.04515163, 0.00555281, 0.18990322, 0.52374277],
       [0.05298918, 0.02287132, 0.26454836, 0.28424806, 0.37534309],
       ...,
       [0.00546348, 0.10114645, 0.05824976, 0.25964209, 0.57549821],
       [0.6925712 , 0.15263935, 0.07239175, 0.06329463, 0.01910307],
       [0.34601683, 0.00590178, 0.20577118, 0.22490436, 0.21740585]])

In [30]:
from sklearn.metrics import confusion_matrix,classification_report

In [31]:
print(confusion_matrix(y_test,predictions))

[[  12   20   36   46  139]
 [  39   45   76   95  215]
 [  84   86  154  191  346]
 [ 134   94  207  379  709]
 [ 389  232  460  762 2096]]


In [32]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         1.0       0.02      0.05      0.03       253
         2.0       0.09      0.10      0.10       470
         3.0       0.17      0.18      0.17       861
         4.0       0.26      0.25      0.25      1523
         5.0       0.60      0.53      0.56      3939

    accuracy                           0.38      7046
   macro avg       0.23      0.22      0.22      7046
weighted avg       0.42      0.38      0.40      7046



In [33]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [34]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace = True)

In [35]:
y = df['Rating']

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,stratify = y,random_state = 192529)

In [37]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True,analyzer = 'word',ngram_range = (2,3),stop_words = 'english',max_features = 5000)

In [39]:
x_train = cv.fit_transform(x_train)
x_test = cv.fit_transform(x_test)

In [40]:
x_train.toarray()
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [42]:
model.fit(x_train,y_train)

MultinomialNB()

In [43]:
predictions = model.predict(x_test)
predictions

array([1., 1., 1., ..., 0., 0., 0.])

In [44]:
from sklearn.metrics import confusion_matrix,classification_report

In [45]:
print(confusion_matrix(y_test,predictions))

[[ 424 1159]
 [1100 4363]]


In [46]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.28      0.27      0.27      1583
         1.0       0.79      0.80      0.79      5463

    accuracy                           0.68      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.68      0.68      0.68      7046

